import { defineConfig, loadEnv } from 'vite';

export default defineConfig(({ mode }) => {
  const env = loadEnv(mode, '.', '');

  // Vercel preview deploys serve the app at the root of an autogenerated
  // subdomain (e.g. grace-groundwater-dashboard-<hash>.vercel.app/), not
  // at the production subpath (/grace-groundwater/). Honoring
  // VITE_BASE_PATH unconditionally would emit asset URLs prefixed with
  // /grace-groundwater/ on a host that serves them at /, producing 404s.
  // Force base to / for any non-production Vercel environment regardless
  // of how the env vars are configured.
  const isVercelNonProd =
    env.VERCEL === '1' && env.VERCEL_ENV !== 'production';

  return {
    base: isVercelNonProd ? '/' : env.VITE_BASE_PATH || '/',
    define: {
      global: 'globalThis',
    },
    optimizeDeps: {
      esbuildOptions: {
        define: {
          global: 'globalThis',
        },
      },
    },
    server: {
      watch: {
        ignored: [
          '**/data_processors/**',
        ],
      },
    },
  };
});
